name: arm

bus:
  device: can0
sync:
  interval_ms: 10
  overflow: 0

defaults:
  eds_pkg: prbt_support
  eds_file: "config/prbt_0_1.dcf"

nodes:
  prbt_joint_1:
    id: 3
  prbt_joint_2:
    id: 4
  prbt_joint_3:
    id: 5
  prbt_joint_4:
    id: 6
  prbt_joint_5:
    id: 7
  prbt_joint_6:
    id: 8
