name: arm

sync:
  interval_ms: 10
  overflow: 0
#heartbeat:
#  rate: 20
#  msg: "77f#05"

defaults:
  eds_pkg: cob_hardware_config
  eds_file: "robots/common/Elmo.dcf"
  #dcf_overlay:
  #  "6083": "1000000" # profile acceleration
  #  "6084": "1000000" # profile deceleration
  #  "60C5": "1000000" # maximum acceleration
  #  "60C6": "1000000" # maximum deceleration
  #  "6099sub1": "100000" # find switch (coarse)
  #  "6099sub2": "10000" # find home (fine)
  #  "1016sub1" : "0x7F0064" # heartbeat timeout of 100 ms for master at 127

  #motor_layer:  # settings passed to motor layer (plugin-specific)
  #  switching_state: 4 # stop motor before switching state

nodes:
    - name: arm_joint_1
      id: 50
      #dcf_overlay:
      #  "6098": "1"            # Homing methods (comes from Elmo)
      #  "6099sub1": "10000.333"    # Homing speed utill reach to swtich (FLS/RLS)
      #  "6099sub2": "10000.333"    # Homing speed from swtich (FLS/RLS) to negative direction
      #  "609A": "10000.333"        # Homing acceleration

      pos_to_device: "(pos / 0.001034507)*962.2126"
      pos_from_device: "(obj6064 * 0.001034507)/962.2126"
      #vel_to_device: "(vel/ 0.001034507)*962.2126"
      #vel_from_device: "(obj606C* 0.001034507)/962.2126"

    - name: arm_joint_2
      id: 10
      pos_to_device: "(-1.0)*(pos * 4000)"
      pos_from_device: "(-1.0)*(obj6064 / 4000 )"
      vel_to_device: "(-1.0)*(vel * 4000)"
      vel_from_device: "(-1.0)*(obj606C / 4000 )"

    - name: arm_joint_3
      id: 20
      pos_to_device: "(pos * 5096)"
      pos_from_device: "(obj6064 / 5096 )"
      vel_to_device: "(vel * 5096)"
      vel_from_device: "(obj606C / 5096 )"

    - name: arm_joint_4
      id: 30
      pos_to_device: "(-1.0)*(pos * 4500)"
      pos_from_device: "(-1.0)*(obj6064 / 4500 )"
      vel_to_device: "(-1.0)*(vel * 4500)"
      vel_from_device: "(-1.0)*(obj606C / 4500 )"
