## joint_names
joint_names: [arm_joint_2,arm_joint_3,arm_joint_4,arm_joint_5]

## control_mode_adapter
max_command_silence: 0.5

## joint_state_controller
joint_state_controller:
    type: joint_state_controller/JointStateController
    publish_rate: 50

## joint trajectory controller
joint_trajectory_controller:
  type: effort_controllers/JointTrajectoryController
  joints:
     - arm_joint_2
     - arm_joint_3
     - arm_joint_4
     - arm_joint_5
  gains: # Required because we're controlling an effort interface
     #arm_joint_1: {p: 100,  d: 1, i: 1, i_clamp: 1}
     arm_joint_2: {p: 100,  d: 1, i: 1, i_clamp: 1}
     arm_joint_3: {p: 100,  d: 1, i: 1, i_clamp: 1}
     arm_joint_4: {p: 100,  d: 1, i: 1, i_clamp: 1}
     arm_joint_5: {p: 100,  d: 1, i: 1, i_clamp: 1}
  constraints:
      goal_time: 0.6
      stopped_velocity_tolerance: 0.05
      #arm_joint_1: {trajectory: 0.1, goal: 0.1}
      arm_joint_2: {trajectory: 0.1, goal: 0.1}
      arm_joint_3: {trajectory: 0.1, goal: 0.1}
      arm_joint_4: {trajectory: 0.1, goal: 0.1}
      arm_joint_5: {trajectory: 0.1, goal: 0.1}
  stop_trajectory_duration: 0.5
  state_publish_rate:  25
  action_monitor_rate: 10
  required_drive_mode: 4


## position controller
joint_group_position_controller:
  type: position_controllers/JointGroupPositionController
  joints:
    #- arm_joint_1
    - arm_joint_2
    - arm_joint_3
    - arm_joint_4
    - arm_joint_5
  required_drive_mode: 1


arm_joint_2_position_controller:
  type: position_controllers/JointPositionController
  joint: arm_joint_2
  required_drive_mode: 1
arm_joint_3_position_controller:
  type: position_controllers/JointPositionController
  joint: arm_joint_3
  required_drive_mode: 1
arm_joint_4_position_controller:
  type: position_controllers/JointPositionController
  joint: arm_joint_4
  required_drive_mode: 1
arm_joint_5_position_controller:
  type: position_controllers/JointPositionController
  joint: arm_joint_5
  required_drive_mode: 1

## velocity controller
joint_group_velocity_controller:
  type: velocity_controllers/JointGroupVelocityController
  joints:
    #- arm_joint_1
    - arm_joint_2
    - arm_joint_3
    - arm_joint_4
    - arm_joint_5
  required_drive_mode: 2


arm_joint_2_velocity_controller:
  type: position_controllers/JointPositionController
  joint: arm_joint_2
  required_drive_mode: 2
arm_joint_3_velocity_controller:
  type: position_controllers/JointPositionController
  joint: arm_joint_3
  required_drive_mode: 2
arm_joint_4_velocity_controller:
  type: position_controllers/JointPositionController
  joint: arm_joint_4
  required_drive_mode: 2
arm_joint_5_velocity_controller:
  type: position_controllers/JointPositionController
  joint: arm_joint_5
  required_drive_mode: 2
