name: gripper

sync:
  interval_ms: 10
  overflow: 0

defaults:
  eds_pkg: cob_hardware_config
  eds_file: "robots/common/Elmo.dcf"

  # canopen_chain_node settings ..
  #motor_allocator: canopen::Motor402::Allocator # select allocator for motor layer

  motor_layer:  # settings passed to motor layer (plugin-specific)
    switching_state: 4 # stop motor before switching state

  #pos_to_device: "rint(rad2deg(pos - 0.17)*80)"
  #pos_from_device: "deg2rad(obj6064)/80 + 0.17"

  #vel_to_device: "rint(rad2deg(vel)*80)"
  #vel_from_device: "deg2rad(obj606C)/80"

  #eff_to_device: "rint(eff)"
  #eff_from_device: "obj6077"

nodes:

  - name: gripper_finger1_joint
    id: 60
    eds_file: "robots/common/Elmo.dcf"
    pos_to_device: "(pos*12000)/1.44"
    pos_from_device: "(obj6064/12000)*1.44"

    vel_to_device: "vel*12000"
    vel_from_device: "obj606C/12000"

  #- name: gripper_small_finger_left_join
    #id: 60
    #eds_file: "robots/common/Elmo.dcf"
